In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import torch

In [4]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [7]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [6]:
points = torch.tensor([4., 1., 5., 3., 2., 1.])
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [15]:
points = torch.tensor([[4., 1.], [5., 3.], [2., 1.]])
points[0, 1]

tensor(1.)

In [11]:
points.shape

torch.Size([3, 2])

In [14]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
some_list = list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [20]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [21]:
img_t = torch.randn(3, 3, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [26]:
batch_t = torch.randn(2, 3, 5, 5) # [batch, channel, rows, columns]

In [27]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([3, 5]), torch.Size([2, 5, 5]))

In [32]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights.shape

torch.Size([3, 1, 1])

In [34]:
img_weights = (img_t * unsqueezed_weights)
img_weights.shape

torch.Size([3, 3, 5])

In [36]:
batch_weights = batch_t * unsqueezed_weights
batch_weights.shape

torch.Size([2, 3, 5, 5])

In [37]:
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

In [39]:
img_gray_weighted.shape, batch_gray_weighted.shape

(torch.Size([3, 5]), torch.Size([2, 5, 5]))

In [40]:
img_gray_weighted_fancy = torch.einsum('...chw, c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw, c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [42]:
double_points = torch.ones(2, 2, dtype=torch.float64)
short_points = torch.tensor([[1, 2], [2, 3]], dtype=torch.short)

In [43]:
double_points * short_points

tensor([[1., 2.],
        [2., 3.]], dtype=torch.float64)

In [46]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(2, 2).short()

In [48]:
double_points = torch.zeros(10, 2).to(torch.float64)
short_points = torch.zeros(2, 2).to(dtype=torch.int16)

In [50]:
a = torch.ones(3, 4, 2)
a_t = torch.transpose(a, 0, 2)
a.shape, a_t.shape

(torch.Size([3, 4, 2]), torch.Size([2, 4, 3]))

In [51]:
a_t = a.transpose(0, 2)
a_t.shape

torch.Size([2, 4, 3])

In [53]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

<ipython-input-53-8575ff47c9e0>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [55]:
points_storage = points.storage()
points_storage[0]

4.0

In [56]:
points.storage()[1]

1.0

In [57]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[2] = 2.0
points

tensor([[4., 1.],
        [2., 3.],
        [2., 1.]])

In [60]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [61]:
second_point.size()

torch.Size([2])

In [63]:
third_point = points[2]
third_point.storage_offset()

4

In [64]:
points.stride()

(2, 1)

In [72]:
a = torch.ones(2)

In [73]:
a

tensor([1., 1.])

In [75]:
a.unsqueeze_(-1).unsqueeze_(-1)
a.shape

torch.Size([2, 1, 1])

In [94]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.shape

torch.Size([3, 2])

In [95]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [98]:
some_t = torch.ones(3, 4, 5)
some_t.stride()

(20, 5, 1)

In [99]:
transpose_t = some_t.transpose(0, 2)
transpose_t.stride()

(1, 5, 20)

In [3]:
import torch
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [4]:
import torch
points = torch.tensor([[4., 1.], [5., 3.], [2., 1.]])
points_np = points.numpy()
points_np

array([[4., 1.],
       [5., 3.],
       [2., 1.]], dtype=float32)

In [6]:
%cd /content/drive/MyDrive/MyStudy/dlwpt-code-ja/p1ch3

/content/drive/MyDrive/MyStudy/dlwpt-code-ja/p1ch3


In [7]:
torch.save(points, '../data/p1ch3/outpoints.t')

In [8]:
#かわりのテンソルの保存方法
with open('../data/p1ch3/outpoints.t', 'wb') as f:
    torch.save(points, f)

In [9]:
points = torch.load('../data/p1ch3/outpoints.t')

In [10]:
import h5py

In [15]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [16]:
f = h5py.File('../data/p1ch3/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]
last_points

array([[5., 3.],
       [2., 1.]], dtype=float32)

In [17]:
last_points_t = torch.from_numpy(dset[-2:])
f.close()

In [18]:
last_points_t

tensor([[5., 3.],
        [2., 1.]])