第3章の章末演習問題

### [1] list(range(9))からテンソルaを作成して、サイズ、オフセット、ストライドを確認してください。
※ ここではGoogle Colaraboratoryでの実行を想定しています。


In [2]:
import torch
a = torch.tensor(list(range(9)))
a.size(), a.storage_offset(), a.stride()

(torch.Size([9]), 0, (1,))

#### （a） b = a.view(3, 3)を使って新しいテンソルを作成します。viewはどんな動作をするのか？またaとbが同じストレージを共有していることを確認してください。

In [3]:
# 回答
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [5]:
b.size(), b.storage_offset(), b.stride()

(torch.Size([3, 3]), 0, (3, 1))

In [4]:
id(b.storage()) == id(a.storage())

<ipython-input-4-17a140b6e870>:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  id(b.storage()) == id(a.storage())


False

#### （b） テンソル c = b[1:,1:]を作成し、サイズ、オフセット、ストライドを確認してください

In [6]:
# 回答
c = b[1:, 1:]
c

tensor([[4, 5],
        [7, 8]])

In [7]:
c.size(), c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

### [2] torch ライブラリからcosineやsquare rootのような数学の演算に対応する関数を見つけてください。

#### （a） 関数を要素ごとに変数aに適用してください。なぜエラーが発生するのでしょう？

In [9]:
# 回答
a_cos = torch.cos(a)
a_cos

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

#### （b） 関数を実行可能にするために、どのような操作が必要なのでしょうか？

In [ ]:
# 回答

#### （c） 何か自作の関数があれば、動かしてみましょう。

In [ ]:
# 省略

以上。
