# [1] モデルをw2 * t_u ** 2 + w1 * t_u + bとして再定義してください
※ ここではGoogle Colaraboratoryでの実行を想定しています。

※ Google Colaraboratoryでbashコマンドを実行するには、命令の前に!をつけます。

In [6]:
import torch
torch.set_printoptions(edgeitems=2, linewidth=75)
import torch.optim as optim

In [2]:
t_c = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0,
                    8.0, 3.0, -4.0, 6.0, 13.0, 21.0])
t_u = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9,
                    33.9, 21.8, 48.4, 60.4, 68.4])
t_un = 0.1 * t_u

In [23]:
def model(t_u, w1, w2, b):
    return w2 * t_u ** 2 + w1 * t_u + b

def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

### （a）再定義を行うために、トレーニングループのどの部分を変更する必要がありますか？

In [ ]:
# 回答

In [44]:
shuffled_indices = torch.randperm(t_c.size(0))
n_vals = int(0.2*t_c.size(0))

train_indices = shuffled_indices[:-n_vals]
val_indices = shuffled_indices[-n_vals:]

train_indices, val_indices

(tensor([ 9,  5, 10,  0,  4,  7,  6,  8,  2]), tensor([1, 3]))

In [45]:
train_t_u = t_u[train_indices]
train_t_c = t_c[train_indices]
val_t_u = t_u[val_indices]
val_t_c = t_c[val_indices]

train_t_un = 0.1 * train_t_u
val_t_un = 0.1 * val_t_u

train_t_un, val_t_un

(tensor([6.0400, 4.8900, 6.8400, 3.5700, 5.6300, 2.1800, 3.3900, 4.8400,
         5.8200]),
 tensor([5.5900, 8.1900]))

In [46]:
def training_loop(n_epochs, optimizer, params, train_t_u, train_t_c, val_t_u, val_t_c):
    for epoch in range(1, n_epochs+1):
        train_t_p = model(train_t_u, *params)
        train_loss = loss_fn(train_t_p, train_t_c)

        with torch.no_grad():
            val_t_p = model(val_t_u, *params)
            val_loss = loss_fn(val_t_p, val_t_c)
            assert val_loss.requires_grad == False

        optimizer.zero_grad()
        train_loss.backward()
        optimizer.step()

        if epoch <= 3 or epoch % 500 == 0:
            print(f'Epoch: {epoch}, Training_loss: {train_loss:.2f}, Validation_loss: {val_loss:.2f}')

In [47]:
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-3
optimizer = optim.SGD([params], lr=learning_rate)

In [49]:
training_loop(
    n_epochs=3000,
    optimizer=optimizer,
    params=params,
    train_t_u=train_t_un,
    train_t_c=train_t_c,
    val_t_u=val_t_un,
    val_t_c=val_t_c
)

Epoch: 1, Training_loss: 1.99, Validation_loss: 20.45
Epoch: 2, Training_loss: 1.99, Validation_loss: 20.45
Epoch: 3, Training_loss: 1.99, Validation_loss: 20.45
Epoch: 500, Training_loss: 1.99, Validation_loss: 20.40
Epoch: 1000, Training_loss: 1.99, Validation_loss: 20.31
Epoch: 1500, Training_loss: 1.98, Validation_loss: 20.21
Epoch: 2000, Training_loss: 1.98, Validation_loss: 20.11
Epoch: 2500, Training_loss: 1.98, Validation_loss: 20.00
Epoch: 3000, Training_loss: 1.98, Validation_loss: 19.90


### （b）モデルが変更されたことを知り得ない部分はどこでしょうか？

In [ ]:
# 回答

### （c）訓練後にロスは高くなりますか、それとも低くなりますか？

In [ ]:
# 回答

###（d）結果は、本章の内容より良くなりますか、それとも悪くなりますか？

In [ ]:
# 回答