In [5]:
a = []
for i in range(10):
    a += [(i, i)]
    print(a)

[(0, 0)]
[(0, 0), (1, 1)]
[(0, 0), (1, 1), (2, 2)]
[(0, 0), (1, 1), (2, 2), (3, 3)]
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)]
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)]
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]


In [6]:
flag = [(True, 1), (True, 2), (False, 3), (True, 46), (False, 2), (False, 4), (True, 33)]

[x for x in flag if x[0]]

[(True, 1), (True, 2), (True, 46), (True, 33)]

In [8]:
import random
random.randrange(0, 32)

22

In [10]:
import numpy as np
a_a = np.array([True, True, False])

In [11]:
import torch
a_t = torch.from_numpy(a_a)
a_t

tensor([ True,  True, False])

In [12]:
a_t.to(torch.long)

tensor([1, 1, 0])

In [79]:
import torch
input_g = torch.tensor([[[1, 2, 3, 4, 3], [4, 5, 7, 3, 1], [2, 1, 6, 0, 4], [2, 3, 4, 1, 1], [2, 3, 4, 1, 1]], [[1, 2, 3, 4, 3], [4, 5, 7, 3, 1], [2, 1, 6, 0, 4], [2, 3, 4, 1, 1], [2, 3, 4, 1, 1]]])

In [80]:
input_g.shape

torch.Size([2, 5, 5])

In [81]:
input_g.unsqueeze_(0)

tensor([[[[1, 2, 3, 4, 3],
          [4, 5, 7, 3, 1],
          [2, 1, 6, 0, 4],
          [2, 3, 4, 1, 1],
          [2, 3, 4, 1, 1]],

         [[1, 2, 3, 4, 3],
          [4, 5, 7, 3, 1],
          [2, 1, 6, 0, 4],
          [2, 3, 4, 1, 1],
          [2, 3, 4, 1, 1]]]])

In [82]:
input_g.to(torch.float32)

tensor([[[[1., 2., 3., 4., 3.],
          [4., 5., 7., 3., 1.],
          [2., 1., 6., 0., 4.],
          [2., 3., 4., 1., 1.],
          [2., 3., 4., 1., 1.]],

         [[1., 2., 3., 4., 3.],
          [4., 5., 7., 3., 1.],
          [2., 1., 6., 0., 4.],
          [2., 3., 4., 1., 1.],
          [2., 3., 4., 1., 1.]]]])

In [83]:
transform_t = torch.eye(3)

In [84]:
for i in range(2):
    transform_t[2, i] = 2

In [85]:
transform_t

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [2., 2., 1.]])

In [86]:
transform_t = transform_t.expand(input_g.shape[0], -1, -1)

In [87]:
transform_t.shape

torch.Size([1, 3, 3])

In [88]:
input_g.shape

torch.Size([1, 2, 5, 5])

In [89]:
transform_t = transform_t.to(input_g.device, torch.float32)

In [90]:
import torch.nn.functional as F
affine_t = F.affine_grid(transform_t[:, :2], input_g.size(), align_corners=False)

In [91]:
augmented_input_g = F.grid_sample(input_g, affine_t, padding_mode="border", align_corners=False)

RuntimeError: ignored

In [27]:
transform_t[:, :2]

torch.Size([4, 2, 2])

In [73]:
%cd /content/drive/MyDrive/MyStudy/dlwpt-code-ja/

/content/drive/MyDrive/MyStudy/dlwpt-code-ja


In [76]:
import sys
sys.path.append('/drive/MyDrive/MyStudy/dlwpt-code-ja/')

In [78]:
from p2ch10.dsets import LunaDataset

ModuleNotFoundError: ignored